name: Merge gh-pages branch to master
on:
  push:
    branches:
      - 'gh-pages'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to master branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAGES_TOKEN}}
